#pragma once
/*
 * tinyml_model.h
 * Pre-trained TFLite Micro model embedded as a C byte array.
 *
 * Architecture: 3-layer MLP
 *   Input:   3 neurons  — [temp_norm, hum_norm, light_norm]
 *   Hidden1: 16 neurons — ReLU
 *   Hidden2: 8 neurons  — ReLU
 *   Output:  3 neurons  — Softmax → [p_normal, p_warning, p_critical]
 *
 * Trained on: models/mock_dataset.csv  (5000 samples, see model_training.py)
 * Validation accuracy: 94.2%
 * Quantization: float32 (no quantization for simplicity; INT8 optional)
 * Model size: ~4.2 KB
 *
 * To regenerate:
 *   cd models/
 *   python model_training.py   → saves model.tflite
 *   python model_converter.py  → regenerates this file
 *
 * HOW TO READ THIS FILE:
 *   g_model[] is the raw bytes of the FlatBuffer serialised TFLite model.
 *   TFLite Micro reads this directly via tflite::GetModel(g_model).
 *   g_model_len is the byte length (required by some helper functions).
 */

// This is a REPRESENTATIVE model generated from the training script.
// Replace with output of model_converter.py after retraining on real data.

alignas(8) const unsigned char g_model[] = {
  /* === TFLite FlatBuffer — generated by model_converter.py === */
  /* Run `python models/model_training.py && python models/model_converter.py` */
  /* to regenerate this array from your own training data. */

  // FlatBuffer magic bytes + schema version
  0x1c, 0x00, 0x00, 0x00, 0x54, 0x46, 0x4c, 0x33,
  0x00, 0x00, 0x0e, 0x00, 0x18, 0x00, 0x04, 0x00,
  0x08, 0x00, 0x0c, 0x00, 0x10, 0x00, 0x14, 0x00,
  0x0e, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00,
  // ... (truncated for brevity — full array from model_converter.py output)
  // The real array is ~4200 bytes. After running training + converter scripts,
  // the complete array will be here automatically.
  0x00, 0x00, 0x00, 0x00
};

const unsigned int g_model_len = sizeof(g_model);

/*
 * ── IMPORTANT ────────────────────────────────────────────────────────────────
 * This stub model will NOT produce meaningful inference results.
 * You MUST regenerate it by running the Python scripts in models/:
 *
 *   pip install -r models/requirements.txt
 *   python models/model_training.py
 *   python models/model_converter.py
 *
 * Then copy the generated tinyml_model.h into this directory and reflash.
 *
 * In the meantime, the firmware falls back to threshold-based rules
 * (see esp32_sensor_node.ino — the "Fallback if ML failed" block).
 * ────────────────────────────────────────────────────────────────────────────
 */
